"""empty message

Revision ID: 17e74cc7a5e1
Revises: 1ef85e211e55
Create Date: 2023-03-06 21:33:26.786361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e74cc7a5e1'
down_revision = '1ef85e211e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lati', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longi', sa.Integer(), nullable=True))
        batch_op.drop_column('coord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coord', sa.VARCHAR(length=360), autoincrement=False, nullable=True))
        batch_op.drop_column('longi')
        batch_op.drop_column('lati')

    # ### end Alembic commands ###
