"""empty message

Revision ID: 18f750befa51
Revises: 0127161bd871
Create Date: 2023-02-09 17:46:20.577128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f750befa51'
down_revision = '0127161bd871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('contacts_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_unique_constraint('contacts_email_key', ['email'])

    # ### end Alembic commands ###
