"""empty message

Revision ID: 1bb7cb88a51c
Revises: 2175f0331f99
Create Date: 2023-03-04 11:52:43.803556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb7cb88a51c'
down_revision = '2175f0331f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
