"""empty message

Revision ID: 1ef85e211e55
Revises: d5b60cb894be
Create Date: 2023-03-05 20:14:41.477054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef85e211e55'
down_revision = 'd5b60cb894be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coord', sa.String(length=360), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('coord')

    # ### end Alembic commands ###
