"""empty message

Revision ID: 3569e1abcf67
Revises: 7dd584d36c5c
Create Date: 2023-03-06 16:31:30.980970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3569e1abcf67'
down_revision = '7dd584d36c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=360),
               type_=sa.String(length=560),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=560),
               type_=sa.VARCHAR(length=360),
               existing_nullable=True)

    # ### end Alembic commands ###
