"""empty message

Revision ID: 3b5165645797
Revises: 9e681356ca19
Create Date: 2023-03-08 19:31:50.094519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5165645797'
down_revision = '9e681356ca19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsvp_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.drop_column('rsvp_status')

    # ### end Alembic commands ###
