"""empty message

Revision ID: 7dd584d36c5c
Revises: 1bb7cb88a51c
Create Date: 2023-03-06 09:25:49.331890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd584d36c5c'
down_revision = '1bb7cb88a51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coord', sa.String(length=360), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('coord')

    # ### end Alembic commands ###
