"""empty message

Revision ID: 9e681356ca19
Revises: 3569e1abcf67
Create Date: 2023-03-06 21:43:30.799376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e681356ca19'
down_revision = '3569e1abcf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lati', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longi', sa.Float(), nullable=True))
        batch_op.drop_column('coord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coord', sa.VARCHAR(length=360), autoincrement=False, nullable=True))
        batch_op.drop_column('longi')
        batch_op.drop_column('lati')

    # ### end Alembic commands ###
