"""empty message

Revision ID: d5b60cb894be
Revises: c639263bc77a
Create Date: 2023-02-26 20:24:48.826238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b60cb894be'
down_revision = 'c639263bc77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
