"""empty message

Revision ID: dc4abf9d8997
Revises: ad1f6ba6ddf4
Create Date: 2023-02-08 09:59:34.243505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4abf9d8997'
down_revision = 'ad1f6ba6ddf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('contacts_email_key', type_='unique')

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('event_guests_contact_email_key', type_='unique')
        batch_op.drop_constraint('event_guests_contact_email_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.drop_column('contact_email')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('guests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.VARCHAR(length=240), autoincrement=False, nullable=False))

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_guests_contact_email_fkey', 'contacts', ['contact_email'], ['email'])
        batch_op.create_unique_constraint('event_guests_contact_email_key', ['contact_email'])
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_unique_constraint('contacts_email_key', ['email'])

    # ### end Alembic commands ###
