import React from "react";
import "../../styles/terms.css"

export const TermsAndConditions = () => {
    return (
        <div className="terms-div">
            <div className="d-flex w-100 justify-content-between">
                <div className="col terms-text">
                    <h1 className="mt-5 mb-5 text-center">Términos y condiciones de uso de ComMeet </h1>
                    <p className="mx-5 mt-3 mb-5">A continuación, figura las Condiciones de uso de nuestra “Plataforma”. Le recomendamos leer el texto completo de las Condiciones de uso porque es nuestro acuerdo legalmente vinculante.
                        Al usar nuestra Plataforma, usted acepta nuestras Condiciones de uso, que representan un acuerdo legalmente vinculante entre usted y ComMeet.
                        Si usted infringe las normas, podemos suspender o cancelar su cuenta. </p>
                    <h5 className="mx-5">Participantes y organizadores</h5>
                    <ol className="mx-5 mt-3 mb-3 col">
                        <li className="mx-5 mt-3 mb-3"> El uso de nuestra Plataforma implica interactuar con personas y hacer cosas en el mundo real, lo que a veces puede conducir a situaciones inesperadas. No podemos controlar lo que sucede en el mundo real y no somos responsables de ello. Utilice el sentido común al interactuar con otras personas.
                            Su contenido y el contenido de otras personas</li>
                        <li className="mx-5 mt-3 mb-3">Usted es responsable de su Contenido, es decir, de cualquier información u otro tipo de material publicado en nuestra Plataforma. Su Contenido debe cumplir con nuestras Condiciones de uso, incluidas las Políticas de uso y de contenido, las Políticas de eventos y las Restricciones para ser miembro. Su Contenido también está sujeto a nuestras Políticas sobre controversias de propiedad intelectual. • No somos responsables del Contenido que publique. Sin embargo, necesitamos que nos otorgue una licencia para usar este Contenido para que podamos mejorar, desarrollar y proteger nuestra Plataforma para usted y otros.</li>
                        <li className="mx-5 mt-3 mb-3">No somos responsables del Contenido publicado por miembros o mensajes publicados por miembros a través de nuestra Plataforma. Por lo general, no revisamos el Contenido antes de que se publique. Si ve Contenido que viola nuestros Términos de uso, puede informarnos sobre el contenido como inapropiado.</li>
                    </ol>
                    <h5 className="mx-5">La plataforma </h5>
                    <ol className="mx-5 mt-3 mb-3">
                        <li className="mx-5 mt-3 mb-3">Intentamos asegurarnos de que nuestra Plataforma esté siempre disponible y funcional, pero no podemos garantizarlo. A veces las cosas no salen según lo planeado. Nos disculpamos de antemano.</li>
                        <li className="mx-5 mt-3 mb-3">Estamos constantemente mejorando nuestra Plataforma. Esto significa que podemos cambiar o descontinuar ciertas características de la misma. • Al utilizarla, acepta las limitaciones y exclusiones de responsabilidad de nuestros Términos de uso. También acepta resolver cualquier disputa que pueda tener con nosotros de la manera descrita en los Términos de uso. Si no vive en la Unión Europea, acepta estar obligado y renuncia a su derecho a buscar protección de un juez o tribunal de justicia. Las reclamaciones solo pueden interponerse a título individual y no como parte de una demanda colectiva.</li>
                        <li className="mx-5 mt-3 mb-3">Es probable que usted resida en un país en el que las leyes vigentes estipulen derechos y obligaciones diferentes o adicionales. Estas Condiciones de uso puntualizarán los ámbitos de divergencia.</li>
                    </ol>
                    <h5 className="mx-5">Condiciones de uso</h5>
                    <p className="mx-5 mt-3 mb-3">Última actualización: 11/2/2023</p>
                    <p className="mx-5 mt-3 mb-3">Nuestras Condiciones de uso contienen información importante sobre sus derechos legales. Para facilitar la comprensión del presente, hemos elaborado resúmenes y consejos en estas casillas grises. Estos resúmenes no forman parte de las condiciones oficiales y es importante que usted lea con atención el contenido de cada sección.</p>
                    <h6 className="mx-5 mt-3 mb-3"><b>1.Este Acuerdo</b><br/></h6>
                    <p className="mx-5 mt-3 mb-3">
                        <b>Resumen:</b>Usted acepta seguir algunas normas básicas cuando use la Plataforma de Meetup. Estas normas se describen en estas Condiciones de uso, incluidas las políticas y pautas relacionadas que se abordan a continuación. Podemos cambiar estas normas.</p>
                    <p className="mx-5 mt-3 mb-3"><b> 1.1 El Acuerdo.</b> ComMeet le permite a usted y a otros miembros organizar eventos o reuniones fuera de Internet, es decir, en el mundo real. Los términos “ComMeet”, “nosotros”, “nos” y “nuestro” se refieren a ComMeet y a nuestras empresas principales, filiales y subsidiarias. Utilizamos los términos “usted” y “su” para hacer referencia a cualquier persona que use nuestra Plataforma y a cualquier empresa o persona que utilice la Plataforma en nombre de una empresa. Utilizamos el término “Plataforma” para hacer referencia a cualquier sitio web, aplicación o servicio ofrecido por ComMeet, incluido el contenido que ofrecemos y las comunicaciones electrónicas que enviamos. Le ofrecemos nuestra Plataforma según estas Condiciones de uso. Utilizamos los términos “Condiciones de uso” y “Acuerdo” de forma intercambiable para hacer referencia a este documento junto con nuestras Políticas de uso y de contenido, Políticas de eventos, Estándares de organizadores y equipos de organización yRestricciones para ser miembro. Al usar la plataforma, usted indica que acepta este Acuerdo. Si utiliza la Plataforma para una empresa, acepta este Acuerdo en nombre de dicha empresa y afirma que tiene la autoridad para vincular dicha empresa a las condiciones establecidas en este Acuerdo. Si usted no acepta o no puede aceptar este Acuerdo, le rogamos que no utilice nuestra Plataforma.</p>
                    <p className="mx-5 mt-3 mb-3"><b>Consejo:</b> Hemos incluido resúmenes y consejos para presentar una visión general de algunos conceptos legales y responder preguntas habituales, pero el texto de estos resúmenes y consejos se ofrece únicamente para facilitar su comprensión y no tiene efecto jurídico alguno.</p>
                    <p className="mx-5 mt-3 mb-3">Estas Condiciones de uso son un acuerdo entre usted y ComMeet, y no entre usted y cualquier otro miembro.</p>
                    <p className="mx-5 mt-3 mb-3"><b>1.2 Revisiones de este Acuerdo.</b> Podemos modificar este Acuerdo cuando corresponda. Si hacemos alguna modificación, se lo comunicaremos; para ello, publicaremos la versión más reciente y actualizaremos la fecha en la parte superior de esta página. En caso de que hagamos una modificación sustancial en este Acuerdo, se lo comunicaremos de alguna otra forma; por ejemplo, le enviaremos un correo electrónico o mostraremos una notificación destacada en nuestra Plataforma. Si usted continúa usando la Plataforma después de la entrada en vigor de cualquier modificación, significará que acepta el Acuerdo revisado. Si no desea aceptar el Acuerdo revisado, puede cerrar su cuenta.</p>
                    <h6 className="mx-5 mt-3 mb-3"><b>2. Su cuenta y ser miembro</b></h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b> Usted necesita tener, como mínimo, 18 años de edad para usar nuestra Plataforma. Los organizadores de ComMeet controlan el Contenido y la pertenencia a los eventos de ComMeet. Sin embargo, podemos eliminar cualquier Contenido que usted publique o cancelar su cuenta en cualquier momento.</p>
                    <p className="mx-5 mt-3 mb-3"><b>2.1 Admisión.</b> Nuestra Plataforma está disponible para cualquier persona que, como mínimo, tenga 18 años de edad. Usted afirma que tiene, como mínimo, 18 años de edad.</p>
                    <p className="mx-5 mt-3 mb-3"><b>2.2. Modificación, suspensión y cancelación de su cuenta.</b> Podemos modificar, suspender o cancelar su cuenta o el acceso a la Plataforma si, a nuestra entera y exclusiva discreción, determinamos que usted ha infringido este Acuerdo, incluidas cualquiera de las políticas o pautas que forman parte de este Acuerdo, que obra en beneficio de la comunidad de ComMeet, o para proteger nuestra marca o Plataforma. Si se diera el caso, le pondremos en conocimiento los motivos de la modificación, suspensión o cancelación de su cuenta. También podemos eliminar cuentas de miembros que estén inactivos durante un periodo prolongado de tiempo. Escríbanos a policy@ComMeet.com si considera que la modificación, suspensión o cancelación de su cuenta se debe a un error.
                    Un miembro que tenga la capacidad de moderar o gestionar una porción en particular de nuestra Plataforma también puede, a su entera y exclusiva discreción, modificar, suspender o cancelar su acceso a dicha porción de la Plataforma.</p>
                    <p className="mx-5 mt-3 mb-3"><b>2.3 Información de la cuenta y seguridad.</b> En el momento de registrarse, usted nos facilita cierta información básica, incluida una dirección de correo electrónico y una contraseña. Mantenga actualizada su dirección de correo electrónico y el resto de la información de su cuenta. Asimismo, usted acepta mantener la seguridad y confidencialidad de su contraseña (de lo contrario, puede que nos veamos obligados a desactivar su cuenta). Le recomendamos encarecidamente que elija una contraseña difícil de intuir y que no utilice en otras cuentas o servicios en línea, y que siga otras prácticas recomendadas de seguridad de contraseñas para evitar, en la medida de lo posible, accesos no autorizados a su cuenta. Usted es el único responsable de las consecuencias por no mantener dicha seguridad y confidencialidad, por ejemplo, si comparte las credenciales de su cuenta con otras personas. Si alguna persona está usando su contraseña o ha accedido a su cuenta sin su permiso, escríbanos a abuse@ComMeet.com. </p>
                    <h6 className="mx-5 mt-3 mb-3"><b>3. Su Contenido y privacidad</b></h6> 
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b> Usted es responsable del Contenido que publique en nuestra Plataforma. Usted nos otorga una licencia para usar este Contenido a fin de hacer funcionar, mejorar, promover y proteger ComMeet y nuestra Plataforma. Nuestra Política de privacidad describe cómo recopilamos y usamos la información que suministra sobre usted mismo y la información que puede estar asociada con usted, y explica las formas limitadas en que podemos compartir esta información.</p>
                    <p className="mx-5 mt-3 mb-3"><b>3.1 Su Contenido. </b>Usted se hace responsable del Contenido que publique en la Plataforma o que, de cualquier otro modo, proporcione a ComMeet. Con el término “Contenido”, nos referimos a la información, al material y a cualquier otro contenido que publique en la Plataforma o que, de algún modo, nos envíe. A continuación, proporcionamos ejemplos de Contenido:
                    • El material que los organizadores y los miembros suelen publicar en la Plataforma, como información sobre los eventos de ComMeet, comentarios y fotos.
                    • Todas las opiniones, sugerencias y otras comunicaciones que usted remita o dirija a ComMeet.</p>
                    <p className="mx-5 mt-3 mb-3">Como responsable de su Contenido, usted acepta, entre otras cosas, que:
                    • Tiene todos los permisos, derechos y licencias necesarios (incluidos los derechos de autor, marcas registradas, derechos contractuales, derechos de privacidad o derechos de publicidad) para facilitar el Contenido a la Plataforma y a ComMeet.
                    • Su Contenido no incluye información personal, privada ni confidencial propiedad de otras personas.
                    • Su Contenido no infringe los derechos de ninguna persona ni entidad.</p>
                    <p className="mx-5 mt-3 mb-3">Usted también acepta que tanto usted como su Contenido cumplan con este Acuerdo, en el que se incluyen nuestras Políticas de uso y de contenido, Políticas de eventos, Estándares de organizadores y equipos de organización, Restricciones para ser miembro, Políticas de propiedad intelectual. Usted, asimismo, acepta que podamos eliminar los metadatos relacionados con su Contenido.</p>
                    <p className="mx-5 mt-3 mb-3"><b>3.2 Licencia otorgada por usted sobre el contenido.</b>No reclamamos la propiedad de su Contenido. Sin embargo, a fin de que podamos hacer funcionar, mejorar, promover y proteger ComMeet y nuestra Plataforma, y para garantizar que no infrinjamos ningún derecho que usted pueda tener respecto a su Contenido, usted, por medio del presente, otorga a ComMeet un derecho y una licencia no exclusivos, internacionales, a perpetuidad, irrevocables, libres de regalías, sublicenciables y transferibles (incluyendo una renuncia a cualquier derecho moral) para usar, alojar, almacenar, reproducir, modificar, publicar, exhibir públicamente, presentar de forma pública y distribuir su Contenido, así como para crear obras derivadas de este y para comercializar y explotar los derechos de autor, la marca registrada, la publicidad y los derechos de base de datos que usted posea sobre su Contenido. Esta licencia permitiría que su Contenido siguiera en la Plataforma, incluso después de que deje de ser miembro de un grupo de ComMeet o de la Plataforma.</p>
                    <p className="mx-5 mt-3 mb-3"><b>Consejo: </b>Esta licencia no nos otorga la propiedad sobre ninguna parte de su Contenido. Simplemente nos otorga a nosotros y a los miembros el derecho de usarlo en relación con la Plataforma. Esta licencia continúa incluso si usted cierra su cuenta porque es necesaria para que podamos hacer funcionar la Plataforma. </p>
                    <p className="mx-5 mt-3 mb-3"><b>3.3 Privacidad. </b> ComMeet recopila la información de registro y otra información sobre usted a través de nuestra Plataforma. Remítase a nuestra Política de privacidad y a la Política de cookies para obtener más información sobre la forma en que recopilamos, usamos y divulgamos esta información. Estas políticas no rigen el uso de la información que usted suministra a terceros, como, por ejemplo, organizadores y otros miembros de la Plataforma de ComMeet. </p>
                    <p className="mx-5 mt-3 mb-3"><b>Consejo: </b> ComMeet no puede controlar la forma en que otros miembros usan la información que usted les suministra; por ende, es muy importante que obre con sentido común y buen criterio al compartir información con otras personas en nuestra Plataforma. </p>
                    <h6 className="mx-5 mt-3 mb-3">4. Su uso de nuestra Plataforma </h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b>Exigimos que usted siga nuestras políticas y pautas al usar nuestra Plataforma. No asumimos responsabilidad alguna por el Contenido que publique cualquier persona en nuestra Plataforma.</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.1 Nuestras políticas, pautas y leyes aplicables. </b> Al utilizar nuestra Plataforma, le exigimos cumplir las Políticas de uso y de contenido, las Políticas de eventos, los Estándares de organizadores y equipos de organización, las Restricciones para ser miembro y las Pautas para el uso de marcas registradas. También acepta cumplir todas las leyes, normas y reglamentos aplicables, y no vulnerar ni infringir los derechos de ningún tercero.
                    La Plataforma hace uso en ocasiones de servicios de terceros para brindar determinadas funciones y servicios a nuestros miembros, unos servicios que podrían solicitar el cumplimiento de las condiciones que rigen sobre tales funciones y servicios. Por ejemplo, algunas áreas de nuestra Plataforma ofrecen servicios de cartografía proporcionados por Google Maps y Google Earth. Al utilizar estos servicios de cartografía en la Plataforma, usted acepta adherirse a las Condiciones de uso adicionales de Google Maps/Google Earth.
                    Si usted infringe este Acuerdo, podemos modificar, suspender o dar de baja su cuenta o acceso a la Plataforma según nuestro exclusivo criterio, en cuyo caso le comunicaremos los motivos correspondientes. Envíe un correo electrónico a policy@ComMeet.com si cree que la modificación, suspensión o cancelación se ha producido por error.</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.2 Contenido de otras personas.</b> ComMeet no controla el Contenido de otros miembros. Si nos enteramos de la existencia de Contenido inapropiado en nuestra Plataforma, nos reservamos el derecho de investigar y tomar las medidas adecuadas, pero no tenemos ninguna obligación de supervisar el Contenido de otros miembros ni asumimos responsabilidad por ello.</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.3 Interacciones con otras personas. </b>  ComMeet no forma parte de ningún plan fuera de línea hecho mediante nuestra Plataforma. ComMeet no realiza ni exige verificaciones de antecedentes a los miembros, y no intenta verificar la veracidad ni la precisión de las declaraciones hechas por los miembros. ComMeet no ofrece declaraciones ni garantías respecto a la conducta o el Contenido de cualquier miembro o a sus interacciones con usted.</p>
                    <p className="mx-5 mt-3 mb-3"><b>Consejo: </b> Obre con sentido común y buen criterio al usar nuestra Plataforma e interactuar con otros miembros, tanto en nuestra Plataforma como en eventos de ComMeet . Si considera que el comportamiento de otro miembro no es adecuado, puede informar de ello escribiendo al correo abuse@ComMeet.com. </p>
                    <p className="mx-5 mt-3 mb-3"><b>4.4 Usos prohibidos de la Plataforma. </b> Nuestra Plataforma contiene información exclusiva y confidencial y se halla protegida por leyes, entre otras, de propiedad intelectual. A menos que lo permitamos expresamente en este Acuerdo, usted acepta, directa o indirectamente, no (a) utilizar, alojar, almacenar, reproducir, modificar, publicar, exhibir y representar públicamente, distribuir o crear productos derivados de la Plataforma o de cualquiera de sus partes; (b) eliminar o alterar los avisos de propiedad de la Plataforma; (c) realizar ingeniería inversa, desensamblar, descompilar o intentar descubrir el código fuente o la estructura, secuencia u organización de la Plataforma, ni tampoco (d) alquilar, arrendar, revender, distribuir o utilizar la Plataforma para fines comerciales no contemplados en este Acuerdo. Usted, asimismo, acepta no utilizar la Plataforma para solicitar o recopilar (i) datos personales de otras personas, salvo cuando sea necesario para la administración o participación en un grupo o evento, ni tampoco (ii) datos personales sensibles, atendiendo a la consideración y tratamiento de los mismos según la ley aplicable (incluyendo, a modo de ejemplo únicamente, información sobre la salud, números de seguridad social u otros identificadores gubernamentales).</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.5 Seguridad de la plataforma. </b> Usted acepta que no podrá, directa ni indirectamente, (a) extraer datos de la Plataforma con fines comerciales no permitidos por estas Condiciones de uso, ya sea mediante el uso de un sistema o software automatizado operado por un tercero o de otro modo (extracción masiva de pantallas, datos o elementos web); (b) participar en cualquier actividad  que interfiera o altere, que esté diseñada para interferir o alterar, o que imponga cargas desproporcionadas a la Plataforma o a sus sistemas. 
                    Usted acepta utilizar, retener y tratar los datos personales obtenidos de la Plataforma con arreglo a las leyes, normas y reglamentos vigentes, y únicamente con el fin de administrar y participar en los eventos de ComMeet. Sin limitación, usted acepta informar a las personas cuyos datos personales desea tratar para obtener los consentimientos necesarios y responder a las solicitudes realizadas por ellas según lo requiera la ley vigente. Usted, asimismo, acepta proteger tales datos frente a accesos o tratamientos no autorizados. Deberá eliminar los datos personales en el momento en que dejen de ser estrictamente necesarios para la administración de un evento de ComMeet o sin demora alguna tras recibir una solicitud de ComMeet, y certificará de inmediato la eliminación de los mismos.</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.6 Modificaciones de la Plataforma. </b>Nos esforzamos por mejorar continuamente nuestra Plataforma. Esto significa que podemos modificar o poner fin a partes o la totalidad de nuestra Plataforma con o sin notificación, y sin incurrir en responsabilidad frente a usted o cualquier tercero.</p>
                    <p className="mx-5 mt-3 mb-3"><b>4.7 Sitios y servicios de terceros. </b>La Plataforma contiene enlaces a sitios de terceros y está integrada con varios servicios, aplicaciones y sitios de terceros que pueden poner su contenido y productos a disposición de usted. No controlamos a estos terceros y no somos responsables de esos sitios o servicios, ni de su contenido o productos. Estos terceros pueden tener sus propias condiciones y políticas, y el uso que usted haga de ellos estará regido por dichas condiciones y políticas. Usted no tiene licencia para utilizar la propiedad intelectual de terceros simplemente por tener acceso a nuestra Plataforma.</p>
                    <h6 className="mx-5 mt-3 mb-3"><b></b>5. Exoneración de responsabilidades </h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b> En la medida en que lo permita la ley vigente, usted acepta no considerarnos responsables de lo que suceda en relación con transacciones con terceros, interacciones entre miembros, o un grupo o evento de ComMeet. También acepta no considerar a los organizadores responsables de negligencias en relación con su Contenido, un grupo o un evento de ComMeet.
                    Usted acepta, en la medida en que lo permita la ley vigente, liberarnos a nosotros y a nuestros ejecutivos, directores, accionistas, agentes, empleados, consultores, empresa principal, filiales, subsidiarias, patrocinadores y otros socios externos (en conjunto, “Partes de ComMeet”) de reclamaciones, demandas y compensaciones por daños y perjuicios (directos y emergentes; en conjunto, “Reclamaciones”), que surjan en relación con cualquier transacción con un tercero, sus interacciones con otros miembros o en relación con un grupo de ComMeet o un evento de ComMeet. Usted también acepta, en la medida en que lo permita la ley vigente, liberar a los organizadores de Reclamaciones basadas en la negligencia de un organizador que surja de su Contenido, un grupo de ComMeet o un evento de ComMeet, o que esté relacionado de alguna manera con ellos.
                    Usted reconoce que algunos eventos de ComMeet conllevan peligros inherentes, como el riesgo de enfermedad, lesiones corporales, discapacidad o muerte. Al participar en estos eventos, comprende y acepta que ha elegido libremente asumir esos riesgos.</p>
                    <h6 className="mx-5 mt-3 mb-3">6. Indemnización</h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b>Usted acepta indemnizarnos hasta el máximo permitido por la ley si recibimos una demanda en relación con el uso que haga de nuestra Plataforma.
                    En la medida en que lo permita la ley vigente, usted acepta indemnizar, defender y exonerar a todas las Partes de ComMeet de toda Reclamación, hecha por un tercero debido a (a) su incumplimiento de este Acuerdo; (b) su uso, mal uso o abuso de nuestra Plataforma; (c) su Contenido; (d) su violación de cualquier ley, estatuto, ordenanza, reglamentación o de los derechos de un tercero, o (e) su participación o conducta en un grupo de ComMeet o en un evento de ComMeet que infrinja este Acuerdo. Usted acepta notificarnos de inmediato sobre cualquier Reclamación de terceros, cooperar con todas las Partes de ComMeet en la defensa de dichas Reclamaciones y pagar todos los honorarios, cobros y gastos asociados con la defensa de dichas Reclamaciones (lo que incluye, entre otros, los honorarios de los abogados). Usted acepta no conciliar ninguna Reclamación sin nuestro previo consentimiento por escrito.</p>
                    <h6 className="mx-5 mt-3 mb-3">7. Exoneración de garantías y limitación de responsabilidad</h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b>Nuestra Plataforma se le suministra “tal cual” y no ofrecemos ninguna garantía de ningún tipo respecto a nuestra Plataforma. Nuestra responsabilidad en relación con la Plataforma está limitada al importe que sea superior entre los dos siguientes: 100 $ o el importe de los cargos durante los doce (12) meses anteriores.</p>
                    <p className="mx-5 mt-3 mb-3"><b>7.1 Exoneración de garantías. </b>Nuestra Plataforma se le proporciona “tal cual” y “según disponibilidad”. En la medida en que lo permita la ley vigente, no asumimos responsabilidad alguna por garantías y condiciones de ningún tipo, lo que incluye, entre otras, las garantías estatutarias y las garantías implícitas de comercialización, idoneidad para un fin determinado y cumplimiento. Asimismo, no asumimos ninguna responsabilidad por cualesquiera garantías respecto a: (a) la fiabilidad, la puntualidad, la precisión y el desempeño de nuestra Plataforma; (b) cualquier información, asesoramiento, servicios o bienes obtenidos mediante nuestra Plataforma o de nosotros, o anunciados en nuestra Plataforma o por nosotros, así como por cualquier información o asesoramiento recibido mediante cualquier enlace a otros sitios web o recursos suministrados mediante nuestra Plataforma; (c) los resultados que puedan obtenerse de la Plataforma; (d) la corrección de cualquier error en la Plataforma; (e) cualquier material o dato obtenido mediante el uso de nuestra Plataforma, y (f) negociaciones con socios de marketing u otros terceros, o como consecuencia de la presencia de estos en nuestra Plataforma o encontrados mediante ella. Es posible que, según la legislación del país en el que reside, le amparen otros derechos. Usted acepta que la vigencia de tales derechos se limitará a aquello que permita la ley vigente.</p>
                    <p className="mx-5 mt-3 mb-3"><b>7.2 Limitación de responsabilidad. </b> En la medida en que lo permita la ley vigente, usted acepta que, en ningún caso, ninguna de las Partes de ComMeet será responsable de ninguno de los daños directos, indirectos, incidentales, especiales o emergentes, lo que incluye, entre otros, los daños por lucro cesante, fondos de comercio, uso, datos u otras pérdidas intangibles (incluso si se ha informado a las Partes de ComMeet de la posibilidad de tales daños) que surjan en relación con: (a) nuestra Plataforma o este Acuerdo, o la imposibilidad de usar nuestra Plataforma (independientemente de la forma en que pudiera suceder, incluida una negligencia por nuestra parte); (b) declaraciones o conducta de cualquier miembro o tercero en la Plataforma, o transacciones con estos; (c) el uso que usted haga de nuestra Plataforma o el traslado hacia o desde eventos de ComMeet, la asistencia a eventos de ComMeet, la participación o exclusión de grupos de ComMeet o eventos de ComMeet, y sus acciones o las de otras personas en los eventos de ComMeet, o (d) cualquier otro asunto relacionado con la Plataforma. Nuestra responsabilidad hacia usted o hacia cualquier tercero en cualquier circunstancia está limitada al importe que sea superior de los dos siguientes: 100 $ o el importe de los cargos, si los hubiera, que usted nos haya pagado durante los 12 meses anteriores a la acción que produjo la responsabilidad. Las limitaciones establecidas anteriormente en esta sección 8 no limitarán ni excluirán la responsabilidad por falta grave, fraude o mala conducta intencionada, malintencionada o imprudente por nuestra parte. Puesto que hay leyes que no contemplan limitaciones ni exclusiones de responsabilidad, es posible que lo mencionado no le afecte. Si reside en la UE, le asisten recursos jurídicos ante pérdidas ocasionadas por incumplimiento o falta de cumplimiento por nuestra parte de nuestras obligaciones legales, o por negligencias que cometamos. Las presentes condiciones no interfieren en los mencionados recursos estatutarios.</p>
                    <h6 className="mx-5 mt-3 mb-3">8. Resolución de controversias </h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b>Si tiene una controversia con ComMeet, acepta intentar resolverla directamente con nosotros primero. Si no podemos alcanzar una solución, lo que ocurre en muy pocos casos, usted debe presentar cualquier controversia con nosotros a un árbitro neutral en lugar de llevar la reclamación a un tribunal. Las reclamaciones solo pueden interponerse a título individual y no como parte de una demanda colectiva. Los miembros residentes en la UE podrían tener derechos adicionales o diferentes con arreglo a la ley vigente. ComMeet no tiene obligación de involucrarse en ninguna controversia que usted tenga con otros miembros, aunque podemos proponer una solución.</p>
                    <p className="mx-5 mt-3 mb-3"><b>8.1 Resolución informal.</b> Antes de hacer una reclamación, usted y ComMeet aceptan intentar resolver cualquier controversia mediante conversaciones de buena fe. Usamos el término “reclamación” en esta sección 8 para hacer referencia a cualquier disputa, reclamación o controversia que surja en relación con el uso que usted haga de nuestra Plataforma o este Acuerdo, lo que incluye su participación en eventos de ComMeet. Usted o ComMeet pueden iniciar este proceso enviando una notificación escrita conforme a la sección 10.2 que describa la controversia y su resolución propuesta. En el caso de que no podamos resolver el asunto en un plazo de 30 días hábiles a partir de la recepción de la notificación inicial, usted o ComMeet pueden presentar una reclamación de conformidad con la sección 8.2. Los miembros residentes en países de la Unión Europea podrían tener derechos adicionales o diferentes con arreglo a lo dispuesto por la ley aplicable.</p>
                    <p className="mx-5 mt-3 mb-3"><b>8.2 Acuerdo de arbitraje.</b> Los procedimientos de arbitraje que constan descritos en esta sección 8.2 se aplican a todos los miembros, excepto a los residentes en países de la Unión Europea. La sección 8.6 expone los procedimientos de resolución de controversias que se aplican a los miembros residentes en países de la Unión Europea.
                    a. Arbitraje obligatorio. Sin perjuicio de lo establecido en la sección 9.3, usted acepta presentar su reclamación a JAMS, Inc. o a su sucesor (“JAMS”) para someterla a un arbitraje definitivo y vinculante. Cabe la posibilidad de que, durante el arbitraje, no podamos valernos de determinados derechos que tanto usted como nosotros solemos tener en los tribunales, como la revelación de pruebas o la apelación. Usted y ComMeet renuncian expresamente al derecho de ser juzgados por un juez o un jurado en un tribunal de justicia. Este acuerdo de arbitraje se aplicará independientemente de si la reclamación se produce durante o con posterioridad a la terminación de este Acuerdo o de su relación con ComMeet.
                    b. Plazo para la presentación en el arbitraje. Cualquier reclamación sujeta a arbitraje debe iniciarse en el plazo de un año a partir de la fecha en que la parte que interpone la reclamación conozca o debiera conocer por primera vez el acto, la omisión o el incumplimiento que da pie a la reclamación, o el periodo más corto que permita la legislación aplicable.
                    c. Procedimientos de arbitraje. Cualquiera de las partes puede iniciar el proceso de arbitraje presentando una demanda por escrito para el arbitraje con JAMS, con copia a la otra parte conforme a los procedimientos de notificación de la sección 11.2. El arbitraje se realizará de conformidad con las normas y procedimientos de arbitraje simplificado de JAMS, y cualquier otra regla aplicable que exija JAMS (“Normas de JAMS”) vigentes en el momento de la demanda de arbitraje. Usted acepta que la Ley Federal de Arbitraje de los EE. UU. y la legislación federal de arbitraje rigen la interpretación y aplicación de estas disposiciones de arbitraje. Toda audiencia de arbitraje tendrá lugar en el condado de Nueva York (Nueva York) u otro lugar según sea exigido por las Normas de JAMS. Su responsabilidad de pagar cualquier cargo de presentación, administrativo y de remuneración de árbitro será únicamente conforme a lo establecido en las Normas de JAMS. Las partes cooperarán con JAMS y entre sí en la programación de los procedimientos de arbitraje y en la elección de un árbitro de la lista apropiada de JAMS con experiencia sustancial en la resolución de controversias de propiedad intelectual y contratos. El árbitro deberá respetar este Acuerdo y, en la medida permitida por las Normas de JAMS, puede obligar al pago de honorarios y gastos, lo que incluye los honorarios de los abogados de la parte ganadora, pero el árbitro no podrá dictar reparación declaratoria ni medidas cautelares que beneficien a cualquier persona diferente de las partes del arbitraje. Podrá dictarse sentencia sobre el laudo emitido por dicho árbitro en cualquier tribunal de jurisdicción competente.</p>
                    <p className="mx-5 mt-3 mb-3"><b>8.3 Excepciones. </b>Usted o ComMeet pueden presentar reclamaciones, si cumplen los debidos requisitos, en tribunales para demandas de menor cuantía en el condado de Nueva York (Nueva York) o en cualquier condado de los EE. UU. donde usted resida o trabaje. Además, tanto usted como ComMeet pueden solicitar medidas cautelares a un tribunal de jurisdicción competente en el condado de Nueva York (Nueva York), según sea necesario para proteger los derechos de propiedad intelectual de usted o de ComMeet, mientras se espera a que finalice el arbitraje. ComMeet puede tomar medidas en el tribunal o arbitraje para cobrar cualquier cargo o recibir compensación por daños y perjuicios por operaciones de la Plataforma o el uso no autorizado de nuestra Plataforma o de la propiedad intelectual, o para solicitar medidas cautelares en relación con lo anterior. Ninguna disposición de esta sección 8 disminuirá el derecho de ComMeet a modificar, suspender o cancelar su cuenta o el acceso a nuestra Plataforma en virtud de la sección 2.2. </p>
                    <p className="mx-5 mt-3 mb-3"><b>8.4 Exclusión del arbitraje. </b> Usted puede rechazar la resolución de controversias mediante arbitraje enviándonos un correo electrónico a arbitration-opt-out@ComMeet .com en un plazo de 30 días a partir de la fecha en la que usted acepta por primera vez este Acuerdo. Su correo electrónico debe incluir su nombre completo, dirección residencial, la dirección de correo electrónico registrada con su cuenta de ComMeet y una declaración clara en la que indique que usted desea excluirse del arbitraje. Si usted se excluye conforme a este proceso, entonces la sección 8.2 de este Acuerdo no se aplica a usted. Esta exclusión no afecta a ninguna otra sección de este Acuerdo, como, por ejemplo, las secciones 8.3 (Excepciones), 8.5 (Renuncia a demandas colectivas), 10.5 (Derecho aplicable), 10.6 (Foro judicial) y 10.7 (Plazo para la presentación).</p>
                    <p className="mx-5 mt-3 mb-3"><b>8.5 Renuncia a demandas colectivas. </b> Usted acepta resolver las controversias con ComMeet de forma individual y no interponer una reclamación como demandante o miembro de una demanda colectiva, acción conjunta o representativa. Usted renuncia expresamente a cualquier derecho de participar en demandas colectivas, arbitrajes colectivos, demandas conjuntas y de interés público con otros arbitrajes. </p>
                    <p className="mx-5 mt-3 mb-3"><b>8.6 Términos de resolución de controversias aplicables a los miembros residentes en países de la UE. </b> Si usted reside en un país de la Unión Europea, se aplicarán las disposiciones imperativas de la ley de su respectivo país. Nada en este Acuerdo repercutirá sobre sus derechos como consumidor ante las disposiciones imperativas de la ley local aplicable. Si usted reside en un país de la Unión Europea, cabe la posibilidad de que las leyes locales de su Estado miembro de la Unión Europea le permitan emprender acciones legales contra ComMeet en su mismo Estado e invocar ciertas leyes locales contra ComMeet. La Comisión Europea pone a su disposición una plataforma en línea de resolución de controversias. </p>
                    <h6 className="mx-5 mt-3 mb-3">9. Propiedad intelectual </h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen:  </b> Si usted usa la marca registrada de ComMeet, asegúrese de cumplir nuestras Pautas para el uso de marcas registradas. Asimismo, no deberá infringir la propiedad intelectual de ninguna persona. Si usted considera que su propiedad intelectual está siendo infringida en cualquier lugar de la Plataforma de ComMeet, siga los procedimientos indicados en nuestras Políticas de controversias de propiedad intelectual.</p>
                    <p className="mx-5 mt-3 mb-3"><b>9.1 Propiedad intelectual de ComMeet. </b>Las marcas registradas, los logotipos, las marcas de servicio y los nombres de servicio de ComMeet son propiedad intelectual de ComMeet. Nuestras Pautas para el uso de marcas registradas explican la forma en que puede o no puede usarlas. Nuestra Plataforma, incluido el material que presentamos en ella, también es propiedad intelectual nuestra o de nuestros licenciantes. Salvo por lo descrito en las Pautas para el uso de marcas registradas, acepta no usar nuestra propiedad intelectual sin nuestro consentimiento previo por escrito. </p>
                    <p className="mx-5 mt-3 mb-3"><b>9.2 Propiedad intelectual de terceros. </b> ComMeet respeta la propiedad intelectual de terceros y solicitamos que nuestros miembros hagan lo mismo. Podemos, en las circunstancias oportunas y a nuestra discreción, retirar el material que, a nuestro juicio, infrinja los derechos de propiedad intelectual de terceros, o desactivar el acceso a dicho material. También podemos restringir o cancelar el acceso a nuestra Plataforma a aquellas personas que consideremos que son infractoras reincidentes. Si considera que se han infringido sus derechos de propiedad intelectual, consulte nuestras Políticas sobre controversias de propiedad intelectual.</p>
                    <h6 className="mx-5 mt-3 mb-3">10. Condiciones generales </h6>
                    <p className="mx-5 mt-3 mb-3"><b>Resumen: </b>Esta sección contiene condiciones que hemos agregado con varios fines. Siga leyendo con atención. </p>
                    <p className="mx-5 mt-3 mb-3"><b>10.2 Avisos. </b> Salvo que se especifique lo contrario en este Acuerdo, o que la ley local lo exija expresamente, todo aviso a ComMeet se debe enviar por correo postal certificado a ComMeet, A/A: Departamento Legal, Madrid, España, o por correo electrónico a legal@ComMeet .com. Todo aviso dirigido a usted se enviará a la dirección de correo electrónico más actual de su cuenta.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.3 Acuerdo completo. </b> Este Acuerdo, incluidas las Políticas de uso y de contenido, las Políticas de eventos, los Estándares de organizadores y equipos de organización, las Restricciones para ser miembro, las Políticas de propiedad intelectual y las Pautas para el uso de marcas registradas constituyen el acuerdo completo entre usted y ComMeet, que sustituye a cualquier acuerdo previo que usted y ComMeet hayan suscrito con el mismo objeto.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.4 Ausencia de agencia. </b>Por medio de este Acuerdo, no se pretende crear ni se crea entre usted y ComMeet una agencia, sociedad, empresa conjunta, relación entre empleado y empleador ni entre las partes que conforman una franquicia. Un miembro de la Plataforma de ComMeet no es un representante ni agente de ComMeet y no puede celebrar un acuerdo en nombre de ComMeet.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.5 Derecho aplicable. </b>Este Acuerdo y la relación entre usted y ComMeet se regirán por las leyes de la Union Europea independientemente de las disposiciones relativas a conflictos de leyes, salvo lo estipulado en la sección 8. </p>
                    <p className="mx-5 mt-3 mb-3"><b>10.6 Foro judicial. </b>Si se concluye que nuestro acuerdo de arbitraje no es aplicable a usted o a su reclamación, o si usted se excluye del arbitraje de conformidad con la sección 8.4., usted y ComMeet aceptan que cualquier procedimiento judicial (salvo las acciones judiciales por demandas de menor cuantía) debe realizarse exclusivamente en los tribunales federales o estatales ubicados en Madrid, España, y que usted y ComMeet aceptan la competencia jurisdiccional y personal de esos tribunales.
                    Además, la Comisión Europea ofrece una plataforma de resolución de disputas en línea para los habitantes de la Unión Europea.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.7. Plazo para la presentación. </b> Cualquier reclamación no sujeta a arbitraje debe iniciarse en el plazo máximo de un año a partir de la fecha en que la parte que interpone la reclamación conozca o debiera conocer por primera vez el acto, la omisión o el incumplimiento que da pie a la reclamación, o el periodo más corto que permita la legislación aplicable. Esta cláusula no le afecta si reside en la UE.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.8 Cesión. </b>Usted no puede ceder, transferir ni sublicenciar este Acuerdo sin el consentimiento previo por escrito de ComMeet, pero este puede ser cedido o transferido por nosotros a cualquier empresa principal, filial o subsidiaria, o por motivo de una fusión, adquisición, reestructuración empresarial, venta de todos o casi todos los activos de ComMeet, o cualquier transacción similar.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.9 Ausencia de renuncias. </b>Si una parte no ejerce ni hace cumplir algún derecho o disposición de este Acuerdo, eso no constituye una renuncia a ese derecho o disposición, y tampoco supone una renuncia a cualquier derecho de actuar con respecto a incumplimientos similares o posteriores.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.10 Nulidad parcial. </b>Si un tribunal competente concluye que alguna de las disposiciones de este Acuerdo no es válida, usted y ComMeet aceptan que el tribunal debe intentar hacer efectivas las intenciones de las partes según se refleje en la disposición y que el resto de disposiciones de este Acuerdo seguirán plenamente vigentes.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.11 Agradecimiento. </b>Le damos nuestro más sincero agradecimiento por leer nuestras Condiciones de uso.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.12 Finalización. </b>Si cancelamos su cuenta o el acceso a nuestra Plataforma, este Acuerdo terminará con respecto a la cuenta del miembro que se ha cancelado, siempre que las disposiciones establecidas en la sección 10.13 sigan en vigor tras dicha finalización.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.13 Preservación de vigencia. </b>Las secciones, 3.2. (Licencia otorgada por usted sobre el contenido), 3.3 (Privacidad), 5 (Exoneración de responsabilidades), 6 (Indemnización), 7 (Exoneración de garantías y limitación de responsabilidad), 8 (Resolución de controversias) y 10 (Condiciones generales) de este Acuerdo y cualquier otra disposición necesaria para dar vigencia a estas disposiciones conservarán su vigencia tras la finalización o el vencimiento de este Acuerdo.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.14 Títulos. </b>Los títulos de las secciones de este Acuerdo existen solo por motivos prácticos y no tienen efecto legal ni contractual. La información contenida en las secciones “Resumen de las Condiciones de uso”, “Consejos” y “Resumen” también responde a una finalidad práctica y no tiene efecto legal ni contractual.</p>
                    <p className="mx-5 mt-3 mb-3"><b>10.15 Infracciones. </b>Le rogamos que nos informe de cualquier infracción de este Acuerdo por parte de un miembro o un tercero enviando un correo electrónico a abuse@ComMeet.com </p>
                </div>
            </div>
        </div>
    );
};